FROM ubuntu:oracular
MAINTAINER Michael Moerz <michael AT moerz dot co dot at .>

ARG version
ARG build_date

#
# TODO: volume for private
#
VOLUME ["/var/lib/samba", "/etc/samba", "/var/log/samba", "/srv/shares"]
ENV DEBIAN_FRONTEND noninteractive

#COPY smb.conf /etc/samba/smb.conf

# PKG: acl for getfacl & setfacl
# winbindd is a must for ac dc
RUN apt-get clean && apt-get update && \
    apt-get install -y attr acl samba smbclient samba-vfs-modules winbind \
                    libnss-winbind libpam-winbind \
                    openssl supervisor
RUN apt-get install -y ldap-utils ldb-tools cifs-utils smbldap-tools 
# tools for debugging
RUN apt-get install -y vim bind9-host krb5-user iputils-ping iproute2
RUN apt-get autoclean && \
    rm -rf /var/cache/apt/archives/*

# create directory for shares not needed is a volume!
#RUN mkdir -f /srv/shares

COPY docker-entrypoint.sh /docker-entrypoint.sh
COPY supervisord.conf /etc/supervisor/supervisord.conf
COPY tools /root/tools
RUN chmod +x /root/tools/*.sh
# backup /var/lib/samba
RUN tar -czf /root/var_lib_samba.tgz /var/lib/samba

LABEL org.label-schema.build-date=$build_date org.label-schema.vcs-url="https://github.com/mmoerz/docker-samba-ad-ac" org.label-schema.vcs-ref=$version org.label-schema.schema-version="1.0"

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["samba"]
