FROM alpine:3.19
MAINTAINER Michael Moerz <michael AT moerz dot co dot at .>

ARG version
ARG build_date

#
# /var/lib/ tdb files and stuff
# /etc/samba configuration files
# /var/log/samba logfiles
# /srv/shares for shares
#
VOLUME ["/var/lib/samba", "/etc/samba", "/var/log/samba", "/srv/shares"]

#COPY smb.conf /etc/samba/smb.conf

# PKG: acl for getfacl & setfacl
# winbindd is a must for ac dc
RUN apk add --no-cache attr acl openssl supervisor \  
     ldb-tools bind krb5 bash perl
RUN apk add --no-cache samba samba-server samba-client \
   samba-libnss-winbind samba-common-tools samba-dc \
   samba-pidl samba-winbind samba-dc-libs samba-doc
RUN apk add iproute2-ss htop bind-tools

COPY docker-entrypoint.sh /docker-entrypoint.sh
COPY supervisord.conf /etc/supervisord.conf
COPY tools /root/tools
RUN chmod +x /root/tools/*.sh

LABEL org.label-schema.build-date=$build_date org.label-schema.vcs-url="https://github.com/mmoerz/docker-samba-ad-ac" org.label-schema.vcs-ref=$version org.label-schema.schema-version="1.0"

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["samba"]
