version: '3.2'

volumes:
  samba_dc1_etc:
    external: true
  samba_dc1_varlib:
    external: true
  samba_dc1_varlog:
    external: true
  samba_dc1_supervisord:
    external: true

  samba_fs1_etc:
    external: true
  samba_fs1_varlib:
    external: true
  samba_fs1_varlog:
    external: true
  samba_fs1_supervisord:
    external: true
  samba_fs1_shares:
    external: true

services:
  samba:
    build: smb-ad-dc
    image: mmoerz/docker-samba-ad-dc:4.16
    hostname: dc1
    privileged: true
    volumes:
      - samba_dc1_etc:/etc/samba
      - samba_dc1_varlib:/var/lib/samba
      - samba_dc1_varlog:/var/log/samba
    env_file:
      - ./samba.env
    networks:
      samba-network:
        ipv4_address: 192.168.1.x

  samba-member:
    command: samba-member
    image: mmoerz/docker-samba-ad-dc:4.16
    hostname: fs1
    privileged: true
    volumes:
      - samba_fs1_etc:/etc/samba
      - samba_fs1_varlib:/var/lib/samba
      - samba_fs1_varlog:/var/log/samba
      - samba_fs1_supervisord:/var/log/supervisord
      - samba_fs1_shares:/shares
    env_file:
      - ./samba-member.env
    networks:
      samba-network:
        ipv4_address: 192.168.1.xx


networks:
  samba-network:
    driver: macvlan
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.0/24
          gateway: 192.168.1.50
    driver_opts:
      parent: br0
  
