version: '3.2'

volumes:
  samba_fs1_etc:
    external: true
  samba_fs1_varlib:
    external: true
  samba_fs1_varlog:
    external: true
  samba_fs1_supervisord:
    external: true
  samba_fs1_shares:
    external: true

services:
  samba-member:
    #command: samba-member
    image: mmoerz/docker-samba-ad-dc:4.20
    hostname: fs1
    domainname: my.domain
    privileged: true
    dns: 10.10.98.12
    volumes:
      - samba_fs1_etc:/etc/samba
      - samba_fs1_varlib:/var/lib/samba
      - samba_fs1_varlog:/var/log/samba
      - samba_fs1_supervisord:/var/log/supervisord
      - samba_fs1_shares:/shares
    env_file:
      - ./samba-member.env
      #environment:
      #  - SAMBA_PROVISION_TYPE=JOIN
      #  - REMOTE_DC=x.x.x.x
      #  - SAMBA_HOSTNAME=fs1
      #  - SAMBA_HOSTIP=x.x.x.x
      #  - SAMBA_DNS_BACKEND=SAMBA_INTERNAL
      #  - SAMBA_DNS_FORWARDER=x.x.x.x
      #  - SAMBA_NOCOMPLEXPWD=true
      #  - SUBNET=x.x.x.x/24
      #  - GATEWAY=x.x.x.x
    networks:
      samba-network:
        ipv4_address: 10.10.98.13

networks:
  samba-network:
    name: samba-network
    external: true
