version: '3.2'

volumes:
  samba_etc:
    external: true
  samba_varlib:
    external: true
  samba_varlog:
    external: true

services:
  samba:
    build: smb-ad-dc
    image: mmoerz/docker-samba-ad-dc:4.15
    hostname: dc1
    privileged: true
    volumes:
      - samba_etc:/etc/samba
      - samba_varlib:/var/lib/samba
      - samba_varlog:/var/log/samba
    env_file:
      - ./samba.env
    ports:
      - 53:53
      - 53:53/udp
      - 88:88
      - 88:88/udp
      - 135:135
      - 137:137
      - 138:138/udp
      - 139:139
      - 389:389
      - 389:389/udp
      - 445:445
      - 464:464
      - 464:464/udp
      - 636:636
      - 3268-3269:3268-3269
    networks:
      samba-network:
        ipv4_address: 192.168.146.53

  samba-member:
    command: samba-member
    image: mmoerz/docker-samba-ad-dc:4.15
    hostname: lex
    privileged: true
    volumes:
      - /srv/samba-lex/etc:/etc/samba
      - /srv/samba-lex/lib:/var/lib/samba
      - /srv/samba-lex/log:/var/log/samba
      - /srv/samba-lex/supervisord:/var/log/supervisord
      - /srv/samba-lex/shares:/shares
    env_file:
      - ./samba-member.env
    networks:
      samba-network:
        ipv4_address: 192.168.146.54


networks:
  samba-network:
    driver: macvlan
    ipam:
      config:
        - subnet: 192.168.146.0/24
          ip_range: 192.168.146.0/24
          gateway: 192.168.146.50
    driver_opts:
      parent: br0
  
