version: '3.2'

services:
  samba:
    build: smb-ad-dc
    image: samba4-ad-dc:4.11
    privileged: true
    network_mode: host
    volumes:
      - ./vol/etc:/etc/samba:rw
      - ./vol/sys:/var/lib/samba:rw
      - ./vol/log:/var/log/samba:rw
      - /srv/shares:/srv/shares:rw
    env_file:
      - ./samba.env
    ports:
      # for details see https://wiki.samba.org/index.php/Samba_AD_DC_Port_Usage
      - 53:53/tcp
      - 53:53/udp
      - 88:88/tcp
      - 88:88/udp
      - 135:135/tcp
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 389:389/tcp
      - 389:389/udp
      - 445:445/tcp
      - 464:464/tcp
      - 464:464/udp
      - 636:636/tcp
      - 3268-3269:3268-3269/tcp
      - 49152-65535:49152-65535/tcp
  
