version: '3.2'

volumes:
  samba_dc1_etc:
    external: true
  samba_dc1_varlib:
    external: true
  samba_dc1_varlog:
    external: true

services:
  samba:
    build: smb-ad-dc
    image: mmoerz/docker-samba-ad-dc:4.16
    hostname: dc1
    privileged: true
    volumes:
      - samba_dc1_etc:/etc/samba
      - samba_dc1_varlib:/var/lib/samba
      - samba_dc1_varlog:/var/log/samba
    env_file:
      - ./samba.env
    networks:
      samba-network:
        ipv4_address: 10.10.98.12
